import { LB_CTA_HTML, LB_FOOTER_HTML, LB_HEADER_HTML } from "@/lib/lb-chrome.generated"

// LicenBase's site header/footer and the licence call to action, rendered from markup generated by
// build_tools_header.py. Static strings, so server and client output cannot differ.
export function LbHeader() {
  return <div id="lb-tools-header" dangerouslySetInnerHTML={{ __html: LB_HEADER_HTML }} />
}

export function LbFooter() {
  return <div id="lb-tools-footer" dangerouslySetInnerHTML={{ __html: LB_FOOTER_HTML }} />
}

export function LbCta() {
  return <div className="contents" dangerouslySetInnerHTML={{ __html: LB_CTA_HTML }} />
}
